# Generated by Django 5.1.5 on 2025-03-15 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('btparlourapp', '0002_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='address',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='name',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='phone_number',
        ),
    ]
