# Generated by Django 5.1.5 on 2025-03-16 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btparlourapp', '0003_remove_admin_address_remove_admin_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_register',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('blocked', 'Blocked')], default='approved', max_length=10),
        ),
    ]
