# Generated by Django 5.1.7 on 2025-03-27 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('btparlourapp', '0005_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
