# Generated by Django 5.1.7 on 2025-03-27 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btparlourapp', '0007_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeautyService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration', models.IntegerField(help_text='Duration in minutes')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/')),
            ],
        ),
    ]
