# Generated by Django 5.1.7 on 2025-03-27 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btparlourapp', '0008_beautyservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beautyservice',
            name='image',
            field=models.ImageField(default='', upload_to='beauty_services/'),
            preserve_default=False,
        ),
    ]
