# Generated by Django 5.1.7 on 2025-03-27 14:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btparlourapp', '0009_alter_beautyservice_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('contact_number', models.CharField(max_length=15)),
                ('special_request', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='btparlourapp.beautyservice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='btparlourapp.tbl_register')),
            ],
        ),
    ]
