# Generated by Django 5.1.7 on 2025-03-27 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('btparlourapp', '0010_servicebooking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceBooking',
        ),
    ]
