# Generated by Django 5.1.7 on 2025-03-27 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btparlourapp', '0011_delete_servicebooking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField()),
                ('booking_time', models.TimeField()),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='btparlourapp.beautyservice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='btparlourapp.tbl_register')),
            ],
        ),
    ]
